### ISSUE TITLE
Add controls for drawing points, lines, and polygons

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-map#18]
We can start with the controls that are included in the Drupal Openlayers module, but it would be great to take it a step farther and improve on those if we can. They are not always easy/intuitive to use - and are challenging on mobile.

The other requirement here will be the ability to extract drawn shapes from the map so that they can be saved by farmOS and/or farmOS-client when a form is submitted.

**Comment by mstenta** [comment]
Might be worth looking at https://github.com/jonataswalker/ol-contextmenu

I wonder if some kind of context menu like that would be easier to use on mobile?

**Comment by mstenta** [comment]
One issue I noticed with `ol-contextmenu` that is a hurdle for using it on mobile: https://github.com/jonataswalker/ol-contextmenu/issues/168

**Comment by mstenta** [comment]
Perhaps worth considering this at the same time: https://github.com/farmOS/farmOS-map/issues/24

**Comment by Skipper-is** [comment]
Quite a nice OL editor: [OpenLayers Editor](http://openlayers-editor.geops.de/). Maybe a bit too much functionality for this and I don't know about mobile optimisation

**Comment by mstenta** [comment]
Wow thanks for sharing that @Skipper-is ! @jgaehring and I were just saying we need to see if a good set of drawing control plugins already exists. This looks pretty nice! We'll have to drop it in and see if it fits all of our needs (or can at least be a starting point).

**Comment by mstenta** [comment]
So I think we have two options for v1.0.0:

1. Simply copy the existing controls from the Drupal OpenLayers Geofield module, so that we at least have feature parity with what the maps in farmOS already have.
2. Use OpenLayers Editor - this will probably require more work, but may result in a better overall editing experience.

Considerations:

- Needs to work on mobile devices (this issue suggests it may need work, but we should test: https://github.com/geops/openlayers-editor/issues/33).
- Needs to be able to draw/modify/delete points/lines/polygons (seems like OLE has all of that).
- Need to be able to extract all drawn geometries so that they can be saved with a Drupal form submission. I assume this won't be hard to do either way.
- Can we put the controls on the bottom of the map, instead of the top right like the OLE demo has them? We already have some controls in the top right (full screen and layer switcher).

**Comment by mstenta** [comment]
After a lot of investigation with @jgaehring we've started a custom Edit control that provides 5 buttons: polygon, line, point, select, and delete. The draw buttons enable the OpenLayers draw interaction. The select button enables the select, modify, and translate interactions. And the delete button deletes any features that are selected by the select interaction.

It's very simple, but seems to work pretty well.  Mobile is usable, but I may iterate on it a bit to improve. For example, right now selecting, modifying, and moving are all enabled at the same time, which works, but sometimes you end up performing a move when you want to modify and vice versa, especially when using your fingers.  So one thing we could consider is splitting those out into separate buttons that are available when a feature is selected (like the delete button).

You can try it out here: https://mstenta.github.io/farmOS-map/

**Comment by mstenta** [comment]
Other things we need to do:

- Enable importing/exporting geometries so they can be loaded/saved.

**Comment by mstenta** [comment]
"Nice to have" enhancements to consider:

- Use SVG icons instead of Unicode characters for buttons.
- Make all the buttons bigger on small screens automatically.
- Add separation between the draw buttons and the select/delete buttons.
- Enable the snap interaction?

**Comment by jgaehring** [comment]
> Enable importing/exporting geometries so they can be loaded/saved.

Working on this now. Like I did [in my own branch](https://github.com/jgaehring/farmOS-map/blob/drawing/src/instance.js#L268), I'm going to create a namespaced property for each desired output format of the geometry. Currently, we only need WKT, so that is the one namespace I will provide. In addition to a getter and setter, I'll have an `.on(eventType, cb)` method for getting the WKT on a given draw/modify/select event.

> Gray out the Delete button when features are not selected (currently being hidden, but there's a CSS style issue because the control container div is still sized to include it).

Noticed this too. My thought was we could set the display to none, instead of setting the visibility to hidden. But we could also grey it out. What do we prefer?

Also noticed there is currently no way to provide a layer as the drawing layer. This is something I'd done in my branch, but then I was not instantiating the map instance with drawing layers enabled, but rather enabling them after the map instance was created. How do want to handle this? We could easily pass a property like `drawingLayer` as a part of the options object, but then I guess there won't be any layers created at that point to pass in, right? So I guess another alternative would be to just use that `wkt.set()` method to add whatever format of pre-existing features to the drawing layer, maybe? Curious your thoughts, @mstenta .

**Comment by jgaehring** [comment]
> Make all the buttons bigger on small screens automatically.

This is just a matter of having a proper html meta tag for the viewport:

```html
<meta name="viewport" content="width=device-width,initial-scale=1.0">
```

This will be a concern of the application code, ultimately, but I have made a change to our index.html so we can work with it in the demo. Preview:

![0 0 0 0_8080_(iPhone 6_7_8)](https://user-images.githubusercontent.com/5556545/65349696-0ff6b980-dbb2-11e9-863c-94eba24ce129.png)

**Comment by mstenta** [comment]
> My thought was we could set the display to none, instead of setting the visibility to hidden.

Oh that could work yea!

> Also noticed there is currently no way to provide a layer as the drawing layer. This is something I'd done in my branch, but then I was not instantiating the map instance with drawing layers enabled, but rather enabling them after the map instance was created. How do want to handle this?

Ah yea, so the Edit control is providing its own layer internally right now.

Would it work for you to instantiate the map with the `{ drawing: true }` options? Or is that difficult?

Seems like it would be best to let the Edit control manage the layer itself, and set up the WKT methods so that they push/pull from that layer.  Would that work?

**Comment by mstenta** [comment]
> This is just a matter of having a proper html meta tag for the viewport:

Ah great!  Can you add that to `static/index.html` as an example?

**Comment by jgaehring** [comment]
> Can you add that to static/index.html as an example?

Yep, I've got a couple things I can commit.

The other thing is setting the display to none. Works like a charm. There is the question of accessibility, which is why `display: none` is often discouraged, but I don't think that's an issue here, since we want that button entirely disabled when there's nothing to delete.

> Seems like it would be best to let the Edit control manage the layer itself, and set up the WKT methods so that they push/pull from that layer. Would that work?

Yea, that's what I was thinking. I can proceed with that if that's what you think would be best. I'll push those other two commits then get working on the getter and setter, and push something up soon so you can take a look.

**Comment by jgaehring** [comment]
> The other thing is setting the display to none. 

Oh and I also made sure that the delete button disappears again after deleting a feature.

**Comment by jgaehring** [comment]
Ok, I've taken a first pass at adding getters, setters and listeners to the Edit control. Here are all my changes:

https://github.com/mstenta/farmOS-map/compare/editcontrol...jgaehring:editcontrol

Let me know what you think, @mstenta.

**Comment by jgaehring** [comment]
Alright, I think I've got this to a pretty fair working state now! I've got field kit using all the different draw/select/modify/translate/delete interactions and it's working pretty well.

I've force pushed a couple more changes to my branch, which again you can see here:

https://github.com/mstenta/farmOS-map/compare/editcontrol...jgaehring:editcontrol

To summarize those changes:
 - Added a meta tag to the index.html head to make sure the controls scale properly
- Restyled the delete button so it's set to `display: none` when no features are selected
- Made sure the delete button goes away after a delete action (since nothing is selected at that point)
- Fixed drawing.js, which was returning `undefined` instead of the `Edit` control itself
- Added `getWKT` method to `Edit` class, a basic getter which returns all the features on the editing layer in WKT format
- Added a `setWKT` method which takes a string in WKT format and sets those features for the edditng layer
- Added the `wktOn` method for adding event listeners to the different editing interactions
- To prevent the Draw listeners from being lost when the `drawInteraction` is reassigned to a new instance of the `Draw` object, I added a property called `drawListeners`, an array of callbacks, which can be re-added as event listeners on the new Draw object.
- Similarly created a `deleteListeners` property, which is an array of callbacks that will be called whenever the delete button is clicked
- Did some refactoring to reuse the projection configuration needed when formatting WKT (see projection.js)

I think that's just about everything.

Some unresolved issues/questions:

- `setWKT` clears all current features on the editing source before adding the features provided as parameter. Do we want this to be the behavior, or do we want it to be something more like `addWKT`?
- I've got WKT hardcoded as the only format for interaction listeners for now. In the future, we may want to accomodate GeoJSON or other formats; this should be pretty simple to achieve with some refactoring.
- It occurs to me, the single 'delete' event listener might be too broad. In the future we might want to differentiate between, say, 'deletefeature' vs 'deletevertex' vs 'deleteall' etc.

**Comment by mstenta** [comment]
@jgaehring Looks great!

I'm still grokking the listeners stuff... it might help to see the relevant code in Field Kit to see how it is used.

Could you break up your last commit into multiple, maybe following the outline of changes you posted in your second to last comment for the commit messages?

> `setWKT` clears all current features on the editing source before adding the features provided as parameter. Do we want this to be the behavior, or do we want it to be something more like `addWKT`?

I think that's fine for now, and suits our current requirements. If we need to be able to "add" WKT to existing drawings in the future, we can consider providing `addWKT` separately I think.

> I've got WKT hardcoded as the only format for interaction listeners for now. 

That's fine - that's all we need currently.

> It occurs to me, the single 'delete' event listener might be too broad. In the future we might want to differentiate between, say, 'deletefeature' vs 'deletevertex' vs 'deleteall' etc.

Agreed. Being able to delete individual vertices would be great, as well as deleting all.

Worth noting: in farmOS right now, the delete button deletes all features. But in farmOS-map it only deletes selected, which is better IMO. Although maybe being able to delete all would still be useful in some cases. I think we can consider both of these as next steps.

**Comment by mstenta** [comment]
> I'm still grokking the listeners stuff...

I think I understand it now. Tell me if this summary is correct:

- We need to be able to allow other code to react when things change in the drawing layer (so that it can be saved to the log if Field Kit, copied to hidden textfield in farmOS, et).
- Since the Draw interaction is destroyed/recreated every time a draw button is clicked, the listeners are lost.
- What you created is a way to save listeners on the Edit class, and then attach/detach them as the Draw interaction is changed.

Makes sense!

**Comment by mstenta** [comment]
Can you also add info to the `README.md` showing how to add listeners?

**Comment by mstenta** [comment]
Oh does this also handle `modify` interactions? Or do we not need to worry about that because the Modify interaction isn't destroyed?

**Comment by mstenta** [comment]
> Oh does this also handle modify interactions? 

Oh duh... I glossed over the `addInteractionListener()` - I see that it does handle modify.

**Comment by jgaehring** [comment]
> Could you break up your last commit into multiple?

Happy to, although I may need to lean on your git expertise to help me do it. Is that something that can be done easily with interactive rebase, or another command?

Agreed on `setWKT` and hardcoding WKT as the only format.

> Being able to delete individual vertices would be great, as well as deleting all. [...] I think we can consider both of these as next steps.

My one misgiving about leaving this to later is that it will change the API. Application code that calls `instance.edit.wktOn('delete', myCallback)` might break in the future, or behave unexpectedly. Perhaps that's fine while we're the only ones using the library; should be easy enough to make necessary changes, but we may want to be careful about such an API becoming entrenched (although I can also think of some easy workarounds that would essentially just interpret `delete` as `deletefeature`).

> I think I understand it now. Tell me if this summary is correct:

Yep! Pretty much, except one thing...

> and then attach/detach them 

We actually don't have a good way of detaching them. I'm on the fence about whether that is necessary, but it might represent an API change if we were to decide to permit that in the future. OL has a way of handling this, with the `.un()` method, but I think it involves returning a key for each listener. Might be worth exploring/considering more before this API design becomes too entrenched.

> Can you also add info to the README.md showing how to add listeners?

Will do. I'll document `getWKT`, `setWKT` and `wktOn`.

> Oh does this also handle modify interactions? Or do we not need to worry about that because the Modify interaction isn't destroyed?

`addInteractionListener` actually does things a little differently, depending on the interaction it's adding the listener to. For modify, translate and select, it's basically just wrapping OL's own event listener and passing a WKT string to the callback instead of the event object. The so-called delete interaction doesn't do that at all, b/c there is no delete interaction in OL. So we basically have to keep track of this ourselves with the deleteListeners member. For the draw interaction we both wrap the OL event listener _and_ keep track of it ourselves, because of the issue that drawInteraction is constantly being reassigned, which is not an issue for modify/translate/select. Also, regarding select: this one's a little different from the rest, because it passes in the WKT only for the feature that's selected, rather than the others, which pass WKT for all features in the drawing layer when the callback is called. This is a bit of a holdover from how I was doing things in featureEditor, where I had the delete button provided by my application code. It's a little weird, but I think it's probably fine.

**Comment by mstenta** [comment]
Great! I think this is looking good! I'm going to merge what we have now in the `editcontrols` branch - it's a good first step that will allow you to move forward with Field Kit release.

> Enable the snap interaction?

We'll defer this for the moment. It isn't needed in Field Kit, and I will be working on integrating farmOS-map into farmOS - where snap interactions will be more useful (assuming mouse-based interactions in desktop environment).

**Comment by mstenta** [comment]
Closed with https://github.com/mstenta/farmOS-map/commit/f1b2b58759bfa42ecf22e847dd83c1b89b958be9

The drawing controls are enabled here so you can test them out: https://farmos.github.io/farmOS-map/
