### ISSUE TITLE
Add Snap interaction

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS-map#24]
Would be really helpful to have layer snapping for editing new/existing geometry. 
OpenLayers has snapping built in:
[See here for an example](https://openlayers.org/en/latest/examples/snap.html)

And [Here for the API reference](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Snap-Snap.html)

**Comment by mstenta** [comment]
Here is the issue for adding the drawing controls, we might consider doing this at the same time: https://github.com/farmOS/farmOS-map/issues/18

**Comment by mstenta** [comment]
Here is the OpenLayers API documentation for the `Snap` interaction: https://openlayers.org/en/latest/apidoc/module-ol_interaction_Snap-Snap.html

**Comment by mstenta** [comment]
This could be useful in both drawing (eg: finishing a polygon) and modifying (moving shapes/vertices).

**Comment by mstenta** [comment]
Reminder: also handle snap interactions with the `featurechange` event type we provide.

**Comment by mstenta** [comment]
Testing this out now - it's pretty easy to implement simple snapping.

It only seems to work when drawing and modifying, not when moving.

Also, and this is a big limitation: it only snaps to a single `source` (the same layer/source that other drawing shapes are in). So it might not be easy to make this snap to shapes on OTHER layers at the same time.

According to the API docs (https://openlayers.org/en/latest/apidoc/module-ol_interaction_Snap-Snap.html), you can initialize the Snap interaction with either a `source` or `features`. Right now I'm testing with the `source`, but maybe if we used `features` we could pass in a combined set of features from other layers as well? I wonder if that would then make it more complicated to snap to the drawing layer, though, because it would need to keep getting updated?

**Comment by mstenta** [comment]
I added the basic snap interaction, which snaps to features in the same drawing layer, as described above.

**Comment by mstenta** [comment]
>  if we used features we could pass in a combined set of features from other layers as well

One of the challenges here is that we don't have access to `this.map` in the `Edit` class constructor, which is where the `Snap` interaction is being initialized. So we can't easily go through all of the map vector layers to build a collection of features.

>  you can initialize the Snap interaction with either a `source` or `features`

Looking at the `Snap.js` code... it looks like precedence is given to `features` over `source`: https://github.com/openlayers/openlayers/blob/3902759595facce80519d512a1ab1999fea1a18b/src/ol/interaction/Snap.js#L235

And there's an `addFeature` method: https://github.com/openlayers/openlayers/blob/3902759595facce80519d512a1ab1999fea1a18b/src/ol/interaction/Snap.js#L195

So... perhaps we could initialize with `features` set to `this.layer.getSource().getFeatures()`, and then when the interaction is added to the map (and we access to `this.map`, then we find and add all the other features). It feels a bit roundabout, but it might work, and might be the only way.

**Comment by mstenta** [comment]
Maybe we need to wait to initialize the `Snap` interaction until `Draw` or `Modify` is added to the map...

**Comment by mstenta** [comment]
Huzzah! I have it working now so that it loads a set of `features` from all map layers - so you can snap to features that are not in the drawing layer!

But......

> I wonder if that would then make it more complicated to snap to the drawing layer, though, because it would need to keep getting updated?

Yup. If you start with a blank drawing layer, and draw a shape, you cannot then snap to that shape. Because it's not being added to `features` automatically. So we need some additional logic that fires whenever a shape is drawn to add that feature to the `features` collection as well.

I wonder if we also need logic to remove them?

**Comment by mstenta** [comment]
> So we need some additional logic that fires whenever a shape is drawn to add that feature to the features collection as well.

Ok, got this working now... not too hard.

But.....

> I wonder if we also need logic to remove them?

Yup. If you draw a feature, and then delete it, then start drawing again, you can still snap to the ghost of where the deleted feature was.

So we need MORE logic that fires when a shape is DELETED to delete it from the `features` collection as well.

Alternatively... maybe we could just make a single function that rebuilds the entire `features` collection from scratch, and just trigger that function to run under each circumstance we need to catch. This might simplify the code, but it would be less efficient.

**Comment by mstenta** [comment]
> So we need MORE logic that fires when a shape is DELETED to delete it from the features collection as well.

Ok, this wasn't too hard either. I was able to do it in the same place that removes the feature from the drawing layer itself.

This resulted in snap logic sprinkled throughout the edit class, however, which I didn't like.

So I refactored a bunch of stuff. Just about done...

**Comment by mstenta** [comment]
I'm going to close this issue. I have a `refactor` branch that takes it one step further (to be able to snap to ALL vector features in ALL layers), but I want to do some more testing before I merge it. And anyway, the basic snapping is done. Case closed!
