### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-map#64]
Should we publish farmOS-map to NPM?

**Comment by mstenta** [comment]
@jgaehring made the point that we might need to rename from `farmOS-map` to `farmos-map` in `package.json`.

**Comment by jgaehring** [comment]
The main benefits I can come up with at the moment are that it would make the library:

- easier to find by other applications/developers
- easier to install by other applications/developers

So I guess the first question is, do we want to prioritize discovery of this library?

My sense at this time is that, no, that is not a priority. This library would be useful to other developers I think only at the point that they are consuming other libraries first, like farmOS.js etc, and potentially `farmLog` (if we make that an independent lib), because until they are able to access and maintain farmOS data, particularly farm geometries and location data, there won't be a need for rendering that data to a map. Maybe if someday we want to put together a farmOS SDK this would be a key component, but I don't think that's on our roadmap at the moment.

**Comment by jgaehring** [comment]
> @jgaehring made the point that we might need to rename from farmOS-map to farmos-map in package.json.

:scream:

**Comment by mstenta** [comment]
> This library would be useful to other developers I think only at the point that they are consuming other libraries first

Our Sci is considering using the library in their PWA and potentially in their Quick Carbon app. The latter does not have any direct connection to farmOS. Just to say that there are some potential use-cases developing... but they can also just do what farmOS-client is doing in `package.json` and reference the GitHub repo directly with `"farmOS-map": "github:farmOS/farmOS-map#v1.0.0"`.

**Comment by jgaehring** [comment]
> Just to say that there are some potential use-cases developing

Oh interesting, not sure I realized that. I guess I'm wondering whether we want to capture third-party developers who might not otherwise be aware it was an option. Folks we're not already working with, or might not ever have a close connection to.

**Comment by mstenta** [comment]
Bumping up the priority of this. We need to be able to pull farmOS-map from NPM (or Bower) in order to include it in farmOS 2.x via Composer. These needs are described in: https://www.drupal.org/project/farm/issues/3186641

**Comment by mstenta** [comment]
Done!

https://www.npmjs.com/package/@farmos.org/farmos-map

And available on asset-packagist.org:

https://asset-packagist.org/package/detail?fullname=npm-asset/farmos.org--farmos-map

Encountered an issue in the process, and implemented a workaround, which I documented here: https://github.com/farmOS/farmOS-map/issues/99
