### ISSUE TITLE
Trying to select layers without editing them

### ISSUE THREAD

**Issue by alexadamsmith** [farmOS/farmOS-map#75]
I'm trying to display layer information when the user clicks on a layer.  Ideally this would be displayed in a popup adjacent to the layer.  

I saw in the readme that you provide a 'select' event when the map is in drawing mode.  I added a listener as follows.
`  if (this.drawing && this.map.edit) {
      this.map.edit.wktOn("select", (wkt) => console.log(wkt));
    }`

I'm able to get a response in the console, but ONLY when I have an editing control active (such as the move layer control with the crossed arrows icon).  Is there an available control that would only select layers, and not edit them?

Thanks so much for your help!!

**Comment by jgaehring** [comment]
Oh, interesting. I think we initially went on the assumption that the `select` functionality was only required for editing activities, as a precursor operation to moving or redrawing the feature (`translate` or `modify` operations). But I can definitely see the usefulness of being able to do that outside of the editing context, like if you wanted to just read out the geometry when it was selected, or even if you hovered over it. Unfortunately, the `select` functionality is embedded in the `Edit` control:

https://github.com/farmOS/farmOS-map/blob/91cc8b687e462f56988b25ed579c43981dba24f1/src/control/Edit/Edit.js#L295-L327

So it won't be possible to enable that on its own without enabling the whole `Edit` control.

However, it is possible to add custom behaviors to the map, which could include your own `Select` interaction, as outlined in the [docs](https://github.com/farmOS/farmOS-map#adding-behaviors): 


```js
import Select from 'ol/interaction/Select'; // you'll need to install the ol pkg from npm for this
import WKT from 'ol/format/WKT'; // for this too

const selectBehavior = {
  attach(instance) {
    const select = new Select();

    select.on('select', (e) => {
      const feat = e.target.getFeatures();
      const wkt = new WKT().writeFeatures(this.getFeatures(), {
        dataProjection: 'EPSG:4326',
        featureProjection: 'EPSG:3857',
      });
      console.log(wkt);
    }

    instance.addInteraction(select);
  },
};

this.map.attachBehavior(selectBehavior);
```

This isn't ideal since it requires importing OL classes independently from farmOS-map, but it could be a good way to prototype what could eventually become a part of the library, like the `'edit'` behavior.

**Comment by mstenta** [comment]
Hi @alexadamsmith 

> I'm trying to display layer information when the user clicks on a layer. Ideally this would be displayed in a popup adjacent to the layer.

This may already be possible, depending on exactly what you want to do! And is different than the concept of "selecting" that is used in the Edit control.

See "Popups" in the readme: https://github.com/farmOS/farmOS-map/#popups

farmOS is using this to create the "area details" popups when you click on an area geometry. Happy to help you figure out how to implement what you want... or point you to examples in the farmOS and farmOS-map codebases for reference.

**Comment by mstenta** [comment]
Here is the relevant behavior in farmOS: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_map/js/farmOS.map.behaviors.popup.js

That works in conjunction with the area type GeoJSON endpoints, which include the area name, etc. So you might be able to do something similar.

**Comment by alexadamsmith** [comment]
Thanks so much for getting back @jgaehring and @mstenta, and thank you for the popup example!  I had been assuming that popups had to be tied to an event (like select), and hadn't realized their true power.  I'm now displaying farm info in a popup when you click on the farm's point on the map, and that's pretty dang cool.

**Comment by mstenta** [comment]
Woo hoo!

I'll close this issue, but feel free to reopen/continue asking related questions here if it's helpful!
