### ISSUE TITLE
Should we convert license from GPLv2 to MIT?

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-map#90]
This is a question to all contributors to farmOS-map, as well as to anyone interested in including farmOS-map in your project.

Right now farmOS-map is licensed under the GPLv2. This means that any project that includes farmOS-map must be licensed similarly. In other words: using farmOS-map in a closed-source project would be in violation of the GPLv2.

If we change the license to MIT, it would allow farmOS-map to be used in more places.\

@jgaehring @paul121 @symbioquine What do you think?

**Comment by mstenta** [comment]
Worth noting, we already changed the license once (from GPLv3 to GPLv2), to make it compatible with Drupal.org packaging requirements (necessary for including farmOS-map in the farmOS Drush Make file, which drupal.org uses to build farmOS).

MIT is also acceptable for Drupal.org packaging.

**Comment by jgaehring** [comment]
I support converting farmOS-map to the MIT license.

**Comment by symbioquine** [comment]
I have no objection to the code I have contributed to farmOS-map being re-licensed under MIT.

@mstenta I am curious though whether there's a way to summarize the "mission" of farmOS/farmOS-map that might help illuminate which license is more appropriate. IANAL, but my understanding is that;
- MIT would be more appropriate if it helps farmOS and/or the farmOS community/mission most to just have more people **using** farmOS - regardless of how or how much they share back.
- GPL would be more appropriate if it is more important for things built using farmOS to themselves be freely shared too.

I tend to license my own projects under MIT since I care more about the idea of having a thriving open source bazaar chock full of awesome tools/libraries than I care about all things being open source ideologically - though that would be great too.

**Comment by mstenta** [comment]
@symbioquine yea my general feeling is that we (the farmOS community) are building both a) monolithic tools (eg: farmOS, Field Kit, Aggregator) and b) reusable components (eg: farmOS.py, farmOS.js, farmOS-map).

I like the idea of making the reusable components available for inclusion in other projects outside of farmOS/Field Kit/Aggregator. Obviously with farmOS.py and farmOS.js, that encourages other platforms to build integrations with farmOS, regardless of whether or not they are open source. This is a good thing, IMO.

**Comment by paul121** [comment]
I agree with those thoughts @symbioquine and @mstenta. I support converting farmOS-map to MIT license.

**Comment by mstenta** [comment]
Thanks all! Let's do this for the next release.

I have to sign off for the day, but if any of you are interested in throwing together a PR please feel free!

**Comment by mstenta** [comment]
Thanks @symbioquine! Merged: https://github.com/farmOS/farmOS-map/commit/a7e121a487f38b2c9e6c17e093b9f8a6599310ba
