### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS-map#97]
Feature request!

It would be nice if core farmOS-map provided some kind of a standard "loading indicator" that behaviors could use without having to implement their own. This would help create a consistent UI across all behaviors using farmOS map.

Just a few ideas:
- Probably a spinner icon? Located in top center? Or a bottom corner?
- Simple ability to turn on/off
- Hovering on the indicator displays an optional description of what is loading
- Indicate completion (steps or % complete, perhaps in the description on hover?)

**Comment by paul121** [comment]
Openlayers actually has a pretty slick example of this for tile layers! https://openlayers.org/en/latest/examples/tile-load-events.html

Using the `tileloadstart` and `tileloadend` events make that fairly easy to implement. It could be nice to add some error handling too via `tileloaderror` - this might help why no base layer is loaded, or at least help indicate that is still loading. Seeing a blank map can be confusing.

Especially for raster layers (and maybe for vector layers, too?) it might be worth including this in the `instance.addLayer()` method options. Core farmOS-map could handle the loading indicator for these layers if `opts.loadingProgress == true`. Other properties could be added such as `opts.loadingDescription = 'Loading mapbox base layers'`, `opts.loadingError = 'Could not load mapbox base layers'`

**Comment by jgaehring** [comment]
I'm having trouble envisioning exactly what this solves. The example from the Openlayers site is cool from a technical standpoint, but it feels redundant to me in that context, because there's already a visual cue that the tiles are rendering, simply because I can see that they are in the process of rendering.

Perhaps you could describe a scenario where the indicator would provide more feedback that isn't automatically available by seeing the tiles as they render? Are you thinking primarily scenarios where the network is just super slow, and hence nothing happens for a number of seconds? (This makes me wonder if it would be worth having some sort of threshold to wait for before displaying the indicator).

**Comment by paul121** [comment]
> The example from the Openlayers site is cool from a technical standpoint, but it feels redundant to me in that context, because there's already a visual cue that the tiles are rendering, simply because I can see that they are in the process of rendering.

Good point @jgaehring. I agree it's not as useful in this context. Network being slow is probably the most common case where it would be useful. I don't think I encounter that issue all too often so maybe that's not necessary!

> (This makes me wonder if it would be worth having some sort of threshold to wait for before displaying the indicator).

Good idea! This makes sense for tile layers that rarely have slow loading times, and perhaps more generally as well. My initial motivations for this were not tile layers though, I just saw that OL example and got excited with other ideas...

> Perhaps you could describe a scenario where the indicator would provide more feedback that isn't automatically available by seeing the tiles as they render?

The first thing that prompted this was actually the loading of Geojson (vector) map layers in farmOS 2.x. Loading all 200 plant asset geometries took ~6 seconds. But once this Geojson response was cached subsequent loads are rendered quite quickly. I should note this isn't the standard farmOS Geojson View. I created a custom Geojson view that includes a few additional fields (such as plant type + crop family) which means there are a few additional joins in the SQL query. I'm sure this impacts the loading time, but I think anyone loading 200+ geometries would still see a few second delay with the standard Geojson View.

The second thing is a custom map behavior that will be loading sensor values, client side, from a 3rd party API. I'd like to render sensor icons on the map while their data is being fetched. This behavior could render it's own loading indicator on the map, but it seems like loading indicator could be generalized and provided for other uses cases too.

**Comment by paul121** [comment]
Oops. This is a duplicate of #10

**Comment by jgaehring** [comment]
> The first thing that prompted this was actually the loading of Geojson (vector) map layers in farmOS 2.x. Loading all 200 plant asset geometries took ~6 seconds.

Ah, that makes sense. (On an unrelated note, I've been thinking about the old `/farm/areas/geojson` endpoint and how that is/will be handled in 2.x :thinking:). Same with the sensor values. Both good scenarios for a loading indicator, I agree!

I wonder if it would be possible to do something like the bar in the Openlayers example, then on hover, the bar expands to be just wide enough to display text with the loading description.

**Comment by paul121** [comment]
> I wonder if it would be possible to do something like the bar in the Openlayers example, then on hover, the bar expands to be just wide enough to display text with the loading description.

That would be slick!

> (On an unrelated note, I've been thinking about the old /farm/areas/geojson endpoint and how that is/will be handled in 2.x thinking)

I'm curious what you're thinking! So far I've largely re-implemented how this worked in 1.x - some info in these two issues: https://www.drupal.org/project/farm/issues/3188579 and https://www.drupal.org/project/farm/issues/3188579. Rather than separate views for areas + assets, I think we support all of our use cases with a single View of Assets. There are some benefits such as being able to match additional filters (only display assets with this flag, or that match a name, etc) which we didn't do before. Want to follow up in those issues?

**Comment by mstenta** [comment]
> Oops. This is a duplicate of #10

Yea FWIW we sort of had this in the old farmOS map (before `farmOS-map`) but it never worked very well IMO and didn't add much value.

I'm open to adding a better solution moving forward though. +1 to all the good thoughts/considerations outlined by @paul121 and @jgaehring above.

**Comment by mstenta** [comment]
Just some quick thoughts on this... working in my local environment and it's clear this will be very helpful.

In the maps that show asset geojson, it can take a few seconds to load lots of geometries in a single layer. And in dashboard and `/assets` pages, there are multiple layers loading - each taking a different amount of time, and no visual cue as to how many have or are still in the process of loading. The only place you can see this is in the Network tab of the browser dev tools.

Because there are potentially multiple layers loading simultaneously, we should think about creating some kind of "loading stack" mechanism - whereby when a layer is added to a map via `addLayer()`, it adds an item to the stack, so that farmOS-map has a concept of "how many" things are loading. The "loading indicator" can then simply be a percentage of how many things are on the stack vs how many have finished loading.

Eg: if there are 10 layers, the indicator could just say "Loading (5/10 layers)" or something like that.

**Comment by symbioquine** [comment]
I just wanted to chime in here on a couple points;

* I agree that a loading indicator for the vector layers could be really helpful, not only because of server-side latency with large numbers of features, but because the client-side loading can take a while on lower powered devices too.
* It's a bit of a tangent, but loading all the current features doesn't necessarily scale super well. Longer term we might want to think about some optimizations along those lines - like rendering zoomed out animal clusters server side as a WMTS combined with WFS at higher zoom levels (to load only the features in view). Obviously, all dependent on folks hitting the scaling limits of the current approach. :)

**Comment by paul121** [comment]
OL v6.14 added a `loadstart` and `loadstop` event which will make implementing a loading indicator much easier: https://github.com/openlayers/openlayers/releases/tag/v6.14.0

**Comment by paul121** [comment]
Just seeing this simple openlayers loading spinner example (believe this became possible with the 6.14 release): https://openlayers.org/en/latest/examples/load-events.html

What would you all think of adding a simple spinner similar to this? It's convenient because it works at the map level using map `loadstart`/`loadend` events, covering all layers.

But to @jgaehring point, this does seem unnecessary for base tile layers because you can often see them loading across the canvas without the need for an indicator. But recently I'm also looking at some raster tile layers from the AU government and sometimes it takes a few seconds before the layer even begins to render in the canvas, so the spinner would still be helpful. 

Maybe there is an argument to include a spinner for everything except base layers?
Or maybe we could have a boolean flag when adding layers to indicate "include in loading indicator" ?

But these ideas would require hooking in at the layer level, so now we've lost the convenience of just using the map `loadstart`/`loadend` events. I'm torn :-/

**Comment by mstenta** [comment]
> recently I'm also looking at some raster tile layers from the AU government and sometimes it takes a few seconds before the layer even begins to render in the canvas, so the spinner would still be helpful.

Agreed. I've experienced this with other slow-loading layers as well. I think it would be worthwhile to implement this.

> Maybe there is an argument to include a spinner for everything except base layers?

If we're going to implement it, I don't see any reason not to use it for all layers. There is no disadvantage to ALSO showing it for base layers, IMO. There is only additional cost in adding conditional logic to prevent it from showing in certain layers it seems.

If it's easy to use the map `loadstart` / `loadend` events, that seems to be a win-win.

Question: do the `loadstart` / `loadend` events only happen when the map is initially loading? Or will the spinner also show when a layer is added to the map *after* it's loaded (eg: via farmOS-map behaviors... or eg: if you start with an invisible layer and then enable it manually).

**Comment by paul121** [comment]
> Question: do the loadstart / loadend events only happen when the map is initially loading? Or will the spinner also show when a layer is added to the map after it's loaded (eg: via farmOS-map behaviors... or eg: if you start with an invisible layer and then enable it manually).

Yes the spinner will show anytime a layer is added. You can also trigger the loading event in custom code via `instance.map.dispatchEvent('loadstart/loadend');` if you wanted custom code to trigger the loading status for other reasons, eg: maybe loading sensor data separate from a map layer.

**Comment by mstenta** [comment]
Closed by https://github.com/farmOS/farmOS-map/pull/187 :tada: 

Thanks @paul121 !!
